/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.numberaddition;

import java.io.BufferedInputStream;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileOutputStream;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.io.ObjectInputStream;
import javax.swing.table.DefaultTableModel;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
       
/**
 *
 * @author student
 */
public class ContactEditor extends javax.swing.JFrame {
    LinkedList<RecIntegral> linkInteg = new LinkedList<>();
    
    /**
     * Creates new form ContactEditor
     */
    public ContactEditor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldUpper = new javax.swing.JTextField();
        jTextFieldLower = new javax.swing.JTextField();
        jTextFieldStep = new javax.swing.JTextField();
        jButtonAdd = new javax.swing.JButton();
        jButtonDel = new javax.swing.JButton();
        jButtonCalc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonOchist = new javax.swing.JButton();
        jButtonZapoln = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemSavetxt = new javax.swing.JMenuItem();
        jMenuItemLoadtxt = new javax.swing.JMenuItem();
        jMenuItemSavebin = new javax.swing.JMenuItem();
        jMenuItemLoadbin = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jTextFieldUpper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUpperActionPerformed(evt);
            }
        });

        jTextFieldLower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLowerActionPerformed(evt);
            }
        });

        jButtonAdd.setText("Добавить");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonDel.setText("Удалить");
        jButtonDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelActionPerformed(evt);
            }
        });

        jButtonCalc.setText("Вычислить");
        jButtonCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcActionPerformed(evt);
            }
        });

        jLabel1.setText("вп");

        jLabel2.setText("tg(x)");

        jLabel3.setText("нп");

        jLabel4.setText("шаг");

        jButtonOchist.setText("Очистить");
        jButtonOchist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOchistActionPerformed(evt);
            }
        });

        jButtonZapoln.setText("Заполнить");
        jButtonZapoln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZapolnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldUpper)
                            .addComponent(jTextFieldLower)
                            .addComponent(jTextFieldStep, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 300, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonZapoln, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonOchist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButtonDel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                    .addComponent(jButtonCalc))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUpper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldStep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdd)
                    .addComponent(jButtonOchist))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonZapoln, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonDel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCalc)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "вп", "нп", "шаг", "результат"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jMenu1.setText("File");

        jMenuItemSavetxt.setText("Save as txt");
        jMenuItemSavetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSavetxtActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSavetxt);

        jMenuItemLoadtxt.setText("Load from txt");
        jMenuItemLoadtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLoadtxtActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemLoadtxt);

        jMenuItemSavebin.setText("Save as bin");
        jMenuItemSavebin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSavebinActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSavebin);

        jMenuItemLoadbin.setText("Load from bin");
        jMenuItemLoadbin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLoadbinActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemLoadbin);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUpperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUpperActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUpperActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
       // TODO add your handling code here:
             try {
        // Парсинг введённых значений
        double vp = Double.parseDouble(jTextFieldUpper.getText());
        double np = Double.parseDouble(jTextFieldLower.getText());
        double step = Double.parseDouble(jTextFieldStep.getText());

        // Нормализация границ
        double lower = Math.min(vp, np);
        double upper = Math.max(vp, np);
        
        // Создание объекта с возможной генерацией исключения
        RecIntegral rec = new RecIntegral(upper, lower, step);
        
        // Добавление в коллекцию и таблицу
        linkInteg.add(rec);
        DefaultTableModel Tmodel = (DefaultTableModel)jTable1.getModel();
        Tmodel.addRow(new Object[] {
            rec.getUpper(), 
            rec.getLower(), 
            rec.getStep()
        });
       
    } catch (NumberFormatException e) {
        // Обработка ошибки парсинга числа
        javax.swing.JOptionPane.showMessageDialog(
            this, 
            "Ошибка: введите корректные числовые значения", 
            "Неверный формат ввода", 
            javax.swing.JOptionPane.ERROR_MESSAGE
        );
    } catch (InvalidException e) {
        // Обработка нашего пользовательского исключения
        javax.swing.JOptionPane.showMessageDialog(
            this, 
            e.getMessage(), 
            "Некорректные данные", 
            javax.swing.JOptionPane.WARNING_MESSAGE
        );
    }
                 
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelActionPerformed
        // TODO add your handling code here:
        int row;
        row = jTable1.getSelectedRow();
               DefaultTableModel Tmodel = (DefaultTableModel)jTable1.getModel();
        if (row != -1){
            Tmodel.removeRow(row);
            linkInteg.remove(row);
        }
        
    }//GEN-LAST:event_jButtonDelActionPerformed

    private void jButtonCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcActionPerformed
        // TODO add your handling code here:
       int row = jTable1.getSelectedRow();
        DefaultTableModel Tmodel = (DefaultTableModel)jTable1.getModel();

    // Проверка: выбрана ли строка
        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(
            this, 
            "Выберите строку для вычисления", 
            "Нет выбора", 
            javax.swing.JOptionPane.INFORMATION_MESSAGE
        );
        return;
    }

        try {
        double lower = Double.parseDouble(Tmodel.getValueAt(row, 1).toString());  
        double upper = Double.parseDouble(Tmodel.getValueAt(row, 0).toString());  
        double step = Double.parseDouble(Tmodel.getValueAt(row, 2).toString());  


        // Проверка шага
        if (step <= 0) {
            Tmodel.setValueAt("Ошибка: шаг > 0", row, 3);
            return;
        }

        RecIntegral rec = new RecIntegral(upper, lower, step);
        double result = rec.Calcint(rec.getUpper(), rec.getLower(), rec.getStep()); 
        
        rec.setResult(result);
        Tmodel.setValueAt(rec.getResult(), row, 3);
        linkInteg.set(row, rec);
            Tmodel.setValueAt(rec.getResult(), row, 3);
            linkInteg.set(row, rec);

        } catch (NumberFormatException e) {
            Tmodel.setValueAt("Ошибка: введите числа", row, 3);
        } catch (Exception e) {
            Tmodel.setValueAt("Ошибка вычисления", row, 3);
            
        } 
             
    }//GEN-LAST:event_jButtonCalcActionPerformed

    private void jTextFieldLowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLowerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLowerActionPerformed

    private void jButtonOchistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOchistActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tModel = (DefaultTableModel)jTable1.getModel();
        tModel.setNumRows(0);
        
    }//GEN-LAST:event_jButtonOchistActionPerformed

    private void jButtonZapolnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZapolnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tModel = (DefaultTableModel)jTable1.getModel();
        tModel.setNumRows(0);
        
        for(RecIntegral item:linkInteg){
            tModel.addRow (new Object[]{
                item.getUpper(),
                item.getLower(),
                item.getStep(),
                item.getResult()
            });
        }
        
    }//GEN-LAST:event_jButtonZapolnActionPerformed

    private void jMenuItemSavetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSavetxtActionPerformed
    JFileChooser f = new JFileChooser();
    FileNameExtensionFilter filter = new FileNameExtensionFilter("Text file (*.txt)", "txt");
    f.setFileFilter(filter);
    f.showSaveDialog(null);
    
    File file = f.getSelectedFile();
    
    if(!file.getPath().endsWith(".txt")){
    file = new File(file.getAbsolutePath() + ".txt");
                }
    try(FileWriter writer = new FileWriter(file,false)){
        for(RecIntegral o : linkInteg){
            writer.write(o.getLower() + " " +
                    o.getUpper() + " " + 
                    o.getStep() + " " +
                    o.getResult() + "\n");
        }
        writer.flush();
        writer.close();
        
    } 
    catch(IOException ex){
        JOptionPane.showMessageDialog(null, ex);
    }
    
         
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemSavetxtActionPerformed

    private void jMenuItemLoadtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLoadtxtActionPerformed
    JFileChooser f = new JFileChooser();
    FileNameExtensionFilter filter = 
            new FileNameExtensionFilter("Text file (*.txt)", "txt");
    f.setFileFilter(filter);
    f.showOpenDialog(null);
    
    File file = f.getSelectedFile(); 
    
    try(BufferedReader reader = new BufferedReader(new FileReader(file))) {
        linkInteg.clear();
        String temp = "";
        while((temp = reader.readLine())!= null){
            String[] part = temp.split(" ");
            linkInteg.add(new RecIntegral(
                Double.parseDouble(part[0]),
                Double.parseDouble(part[1]),
                Double.parseDouble(part[2]),
                Double.parseDouble(part[3])
            ));
        };
    
        reader.close();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        linkInteg.forEach((RecIntegral obj) -> {
            model.addRow(
            new Object[]{obj.getLower(), 
                obj.getUpper(), 
                obj.getStep(), 
                obj.getResult()
            });
        });
    }
    catch(IOException ex){
        JOptionPane.showMessageDialog(null, ex);
    }
    catch(InvalidException exe){
        JOptionPane.showMessageDialog(null, exe);}
    }//GEN-LAST:event_jMenuItemLoadtxtActionPerformed

    private void jMenuItemSavebinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSavebinActionPerformed
    JFileChooser f = new JFileChooser();
    FileNameExtensionFilter filter = 
            new FileNameExtensionFilter("Binary file (*.bin)", "bin");
    f.setFileFilter(filter);
    f.showSaveDialog(null);
     File file = f.getSelectedFile(); 
     
     if(!file.getPath().endsWith (".bin"))
    {
         file = new File(file.getPath() + ".bin");
    }
    try(ObjectOutputStream out = new ObjectOutputStream(new FileOutputStream(file)))
    {
        out.writeObject(linkInteg);
        out.flush();
        out.close();
    }
    catch(IOException ex){
        JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jMenuItemSavebinActionPerformed

    private void jMenuItemLoadbinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLoadbinActionPerformed
    JFileChooser f = new JFileChooser();
    FileNameExtensionFilter filter = new FileNameExtensionFilter("Binary file (*.bin)", "bin");
    f.setFileFilter(filter);
    f.showOpenDialog(null);
    
    File file = f.getSelectedFile(); 
    
    try(ObjectInputStream in = new ObjectInputStream(new BufferedInputStream(new FileInputStream(file))))
    {
        linkInteg = (LinkedList<RecIntegral>)in.readObject();
        in.close();
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        linkInteg.forEach((RecIntegral obj) -> {
            model.addRow(new Object[]{obj.getLower(), obj.getUpper(), obj.getStep(), obj.getResult()});
        });
    }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
    }
    }//GEN-LAST:event_jMenuItemLoadbinActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContactEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContactEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContactEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContactEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContactEditor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonCalc;
    private javax.swing.JButton jButtonDel;
    private javax.swing.JButton jButtonOchist;
    private javax.swing.JButton jButtonZapoln;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemLoadbin;
    private javax.swing.JMenuItem jMenuItemLoadtxt;
    private javax.swing.JMenuItem jMenuItemSavebin;
    private javax.swing.JMenuItem jMenuItemSavetxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldLower;
    private javax.swing.JTextField jTextFieldStep;
    private javax.swing.JTextField jTextFieldUpper;
    // End of variables declaration//GEN-END:variables
}
